[versions]

# Android
agp = "8.12.2"

# Kotlin
kotlin = "2.2.10"
kotlin-immutable = "0.4.0"
kotlin-coroutines = "1.10.2"
kotlin-serialization = "1.9.0"
kotlin-datetime = "0.7.1"
ksp = "2.2.0-2.0.2"

# AndroidX
androidx-core = "1.17.0"
androidx-activity = "1.10.1"
androidx-hilt = "1.2.0"
androidx-media3 = "1.8.0"
androidx-lifecycle = "2.9.3"
androidx-compose-material3 = "1.3.2"
androidx-navigation = "2.9.3"
androidx-security = "1.1.0"
androidx-compose-bom = "2025.08.01"
androidx-startup = "1.2.0"
androidx-window = "1.4.0"
androidx-splash = "1.2.0-rc01"

# Google
dagger = "2.57.1"

# Network
retrofit = "3.0.0"
okhttp = "5.1.0"
eithernet = "2.0.0"

# Static analysis
detekt = "1.23.8"
lint-compose = "1.4.2"

# Debug
richeditorCompose = "1.0.0-rc13"
roomRuntime = "2.7.2"
timber = "5.0.1"
hyperion = "0.9.38"
configVars = "4.0.8"

# Others
desugaring = "2.1.5"
coil = "2.7.0"
grgit = "5.3.3"
javax-inject = "1"
lottie = "6.6.7"
sentry-plugin = "5.9.0"
sentry = "8.20.0"

# Test
espressoCore = "3.6.1"

# Dependencies of the included build-logic
androidTools = "31.13.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCoreVersion = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"

[libraries]

# Kotlin
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-material3" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlin-coroutines" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }

# Androidx
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", name = "compose-foundation" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", name = "lifecycle-compose", version.ref = "androidx-lifecycle" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-security = { module = "androidx.security:security-crypto", version.ref = "androidx-security" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }
androidx-splash = {module = "androidx.core:core-splashscreen", version.ref = "androidx-splash"}

# Network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-kotlinSerializationConverter = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
eithernet = { module = "com.slack.eithernet:eithernet", version.ref = "eithernet" }

# Testing
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# Google
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "dagger" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }

# Static analysis
lint-compose = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "lint-compose" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Debug
richeditor-compose = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "richeditorCompose" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
sentry = { group = "io.sentry", name = "sentry-android", version.ref = "sentry" }
sentry-compose = { group = "io.sentry", name = "sentry-compose-android", version.ref = "sentry" }

#Media3
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "androidx-media3" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "androidx-media3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "androidx-media3" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "androidx-media3" }
androidx-media3-datasource = { group = "androidx.media3", name = "media3-datasource", version.ref = "androidx-media3" }
androidx-media3-datasource-cronet = { group = "androidx.media3", name = "media3-datasource-cronet", version.ref = "androidx-media3" }

# Others
android-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
grgit-gradlePlugin = { group = "org.ajoberstar.grgit", name = "org.ajoberstar.grgit.gradle.plugin", version.ref = "grgit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCoreVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
sentry = { id = "io.sentry.android.gradle", version.ref = "sentry-plugin" }

# Convention plugins
dalmif-android-application = { id = "dalmif.android.application" }
dalmif-android-application-compose = { id = "dalmif.android.application.compose" }
dalmif-android-library = { id = "dalmif.android.library" }
dalmif-android-library-compose = { id = "dalmif.android.library.compose" }
dalmif-android-hilt = { id = "dalmif.android.hilt" }
dalmif-android-media = { id = "dalmif.android.media" }
dalmif-android-feature = { id = "dalmif.android.feature" }
dalmif-android-lint = { id = "dalmif.android.lint" }
dalmif-jvm-library = { id = "dalmif.jvm.library" }
dalmif-detekt = { id = "dalmif.detekt" }
dalmif-git-versioning = { id = "dalmif.git.versioning" }
dalmif-kotlin-serialization = { id = "dalmif.kotlin.serialization" }
dalmif-secrets = { id = "dalmif.secrets" }
dalmif-sentry = { id = "dalmif.sentry" }