complexity:
  active: false

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Z0-9]*'
  MatchingDeclarationName:
    excludes:
      - "**/*Navigation.kt"

style:
  MagicNumber:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ '*Preview*' ]
  ForbiddenComment:
    active: false